### ISSUE TITLE
[BUG] GraphCanvasSizeProportional Cause Exception when Init Few Nodes and then Mutate More

### ISSUE THREAD

**Issue by PatrickStar125** [cupofme/force_directed_graphview#41]
## How problem happened
When I first built GraphView without any node and set `canvasSize: const GraphCanvasSizeProportional()` , I will get an empty Graph normally. Then I did a query and try to refresh the graph,  the exception happened. 

```dart
if (result != null) {
  graph.copy(Graph.fromStandardResult(result));
  setState(() {
    _refreshGraph();
  });
}
```
```dart
void _refreshGraph() {
     //  .....
    _controller.mutate((mutator) {
      mutator.clear();
      nodes.forEach((_, node) => mutator.addNode(node));
      for (final r in graph.relations) {
        mutator.addEdge(
          Edge(
            source: nodes[r.$1]!,
            destination: nodes[r.$3]!,
            data: graph.predicates[r.$2]!,
          ),
        );
      }
    });
  }
````
![image](https://github.com/cupofme/force_directed_graphview/assets/51241767/08e41f16-0aef-4815-b1c3-2c61b22a8d50)

I check the code and found that 
[github.com/cupofme/force_directed_graphview/blob/main/lib/src/controller.dart?plain=1#L169](https://github.com/cupofme/force_directed_graphview/blob/3ee7f5a8042707af4e231f4bb652c4933353f86a/lib/src/controller.dart#L169)
`_applyConfiguration` will only be called when `GraphView` call `initController`, so `_controller._currentSize` will not update when graph relayout.

## Fix:
[github.com/cupofme/force_directed_graphview/blob/main/lib/src/controller.dart?plain=1#L10](https://github.com/cupofme/force_directed_graphview/blob/3ee7f5a8042707af4e231f4bb652c4933353f86a/lib/src/controller.dart#L10)
change
```dart
GraphCanvasSize? _canvasSize;
Size? get _currentSize => _canvasSize?.resolve(nodes: nodes, edges: edges);
```

[github.com/cupofme/force_directed_graphview/blob/main/lib/src/controller.dart?plain=1#L169](https://github.com/cupofme/force_directed_graphview/blob/3ee7f5a8042707af4e231f4bb652c4933353f86a/lib/src/controller.dart#L169)
```dart
Future<void> _applyConfiguration({
    required GraphLayoutAlgorithm algorithm,
    required GraphCanvasSize size,
    required LazyBuilding lazyBuilding,
    required TransformationController transformationController,
  }) async {
    _lazyBuilding = lazyBuilding;
    transformationCtl = transformationController;
    _currentAlgorithm = algorithm;

// CHANGE HERE
    _canvasSize = size;

    final layoutStream = algorithm.layout(
      nodes: _nodes,
      edges: _edges,
      size: canvasSize,
    );

    await for (final layout in layoutStream) {
      _layout = layout;

      if (!_centered) {
        jumpToCenter();
        _centered = true;
      }
      notifyListeners();
    }
  }
```

**Comment by cupofme** [comment]
Fix available in 0.6.2. Thanks for contribution!
